CRITICAL - 2022-04-11 09:59:51 --> Too few arguments to function App\Controllers\registroCrud::ver(), 0 passed in /app/myapp/system/CodeIgniter.php on line 832 and exactly 1 expected
#0 /app/myapp/system/CodeIgniter.php(832): App\Controllers\registroCrud->ver()
#1 /app/myapp/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController()
#2 /app/myapp/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest()
#3 /app/myapp/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-04-11 10:12:58 --> Too few arguments to function App\Controllers\registroCrud::ver(), 0 passed in /app/myapp/system/CodeIgniter.php on line 832 and exactly 1 expected
#0 /app/myapp/system/CodeIgniter.php(832): App\Controllers\registroCrud->ver()
#1 /app/myapp/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController()
#2 /app/myapp/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest()
#3 /app/myapp/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-04-11 11:28:47 --> Argument 1 passed to App\Models\UsuarioModel::unUsuario() must be of the type int, string given, called in /app/myapp/app/Controllers/LoginLogOutController.php on line 40
#0 /app/myapp/app/Controllers/LoginLogOutController.php(40): App\Models\UsuarioModel->unUsuario()
#1 /app/myapp/system/CodeIgniter.php(832): App\Controllers\LoginLogOutController->login02Validar()
#2 /app/myapp/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController()
#3 /app/myapp/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest()
#4 /app/myapp/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2022-04-11 13:33:43 --> Error connecting to the database: Connection refused
CRITICAL - 2022-04-11 13:33:43 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
#0 /app/myapp/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /app/myapp/system/Database/BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#2 /app/myapp/system/Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 /app/myapp/system/BaseModel.php(584): CodeIgniter\Model->doFindAll()
#4 /app/myapp/app/Models/registroModel.php(64): CodeIgniter\BaseModel->findAll()
#5 /app/myapp/app/Controllers/RegistroCrud.php(15): App\Models\registroModel->todEs()
#6 /app/myapp/system/CodeIgniter.php(832): App\Controllers\registroCrud->index()
#7 /app/myapp/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController()
#8 /app/myapp/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest()
#9 /app/myapp/public/index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-04-11 13:35:26 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: Name or service not known
CRITICAL - 2022-04-11 13:35:26 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: Name or service not known
#0 /app/myapp/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /app/myapp/system/Database/BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#2 /app/myapp/system/Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 /app/myapp/system/BaseModel.php(584): CodeIgniter\Model->doFindAll()
#4 /app/myapp/app/Models/UsuarioModel.php(31): CodeIgniter\BaseModel->findAll()
#5 /app/myapp/app/Controllers/LoginLogOutController.php(21): App\Models\UsuarioModel->todos()
#6 /app/myapp/system/CodeIgniter.php(832): App\Controllers\LoginLogOutController->login01Formulario()
#7 /app/myapp/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController()
#8 /app/myapp/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest()
#9 /app/myapp/public/index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-04-11 13:37:40 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: Name or service not known
CRITICAL - 2022-04-11 13:37:40 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: Name or service not known
#0 /app/myapp/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /app/myapp/system/Database/BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#2 /app/myapp/system/Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 /app/myapp/system/BaseModel.php(584): CodeIgniter\Model->doFindAll()
#4 /app/myapp/app/Models/UsuarioModel.php(31): CodeIgniter\BaseModel->findAll()
#5 /app/myapp/app/Controllers/LoginLogOutController.php(21): App\Models\UsuarioModel->todos()
#6 /app/myapp/system/CodeIgniter.php(832): App\Controllers\LoginLogOutController->login01Formulario()
#7 /app/myapp/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController()
#8 /app/myapp/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest()
#9 /app/myapp/public/index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-04-11 14:17:36 --> Error connecting to the database: Connection refused
CRITICAL - 2022-04-11 14:17:36 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
#0 /app/myapp/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /app/myapp/system/Database/BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#2 /app/myapp/system/Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 /app/myapp/system/BaseModel.php(584): CodeIgniter\Model->doFindAll()
#4 /app/myapp/app/Models/UsuarioModel.php(31): CodeIgniter\BaseModel->findAll()
#5 /app/myapp/app/Controllers/LoginLogOutController.php(21): App\Models\UsuarioModel->todos()
#6 /app/myapp/system/CodeIgniter.php(832): App\Controllers\LoginLogOutController->login01Formulario()
#7 /app/myapp/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController()
#8 /app/myapp/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest()
#9 /app/myapp/public/index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-04-11 14:25:10 --> Error connecting to the database: Connection refused
CRITICAL - 2022-04-11 14:25:10 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
#0 /app/myapp/system/Database/BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 /app/myapp/system/Database/BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#2 /app/myapp/system/Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 /app/myapp/system/BaseModel.php(584): CodeIgniter\Model->doFindAll()
#4 /app/myapp/app/Models/UsuarioModel.php(31): CodeIgniter\BaseModel->findAll()
#5 /app/myapp/app/Controllers/LoginLogOutController.php(21): App\Models\UsuarioModel->todos()
#6 /app/myapp/system/CodeIgniter.php(832): App\Controllers\LoginLogOutController->login01Formulario()
#7 /app/myapp/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController()
#8 /app/myapp/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest()
#9 /app/myapp/public/index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-04-11 20:21:08 --> View themes, no current section.
#0 /app/myapp/app/Views/login/login01Formulario.php(47): CodeIgniter\View\View->endSection()
#1 /app/myapp/system/View/View.php(210): include('/app/myapp/app/...')
#2 /app/myapp/system/View/View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 /app/myapp/system/Common.php(1089): CodeIgniter\View\View->render()
#4 /app/myapp/app/Controllers/LoginLogOutController.php(23): view()
#5 /app/myapp/system/CodeIgniter.php(832): App\Controllers\LoginLogOutController->login01Formulario()
#6 /app/myapp/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController()
#7 /app/myapp/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest()
#8 /app/myapp/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-04-11 20:40:14 --> syntax error, unexpected 'as' (T_AS), expecting ')'
#0 /app/myapp/system/View/View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 /app/myapp/system/Common.php(1089): CodeIgniter\View\View->render()
#2 /app/myapp/app/Controllers/LoginLogOutController.php(23): view()
#3 /app/myapp/system/CodeIgniter.php(832): App\Controllers\LoginLogOutController->login01Formulario()
#4 /app/myapp/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController()
#5 /app/myapp/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest()
#6 /app/myapp/public/index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-11 21:16:03 --> Call to a member function sizeof() on array
#0 /app/myapp/system/CodeIgniter.php(832): App\Controllers\LoginLogOutController->login02Validar()
#1 /app/myapp/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController()
#2 /app/myapp/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest()
#3 /app/myapp/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-04-11 21:16:11 --> Call to a member function sizeof() on array
#0 /app/myapp/system/CodeIgniter.php(832): App\Controllers\LoginLogOutController->login02Validar()
#1 /app/myapp/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController()
#2 /app/myapp/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest()
#3 /app/myapp/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-04-11 21:16:23 --> Call to a member function sizeof() on array
#0 /app/myapp/system/CodeIgniter.php(832): App\Controllers\LoginLogOutController->login02Validar()
#1 /app/myapp/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController()
#2 /app/myapp/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest()
#3 /app/myapp/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
